src/main/routes.py
from flask import render_template, request, Blueprint, jsonify, flash, redirect, url_for, abort, make_response,\
                current_app, session
from src.models import User, Notification, PaperGradingKullanimi, BireyselFatura, Tag, Hangiders
from flask_login import login_user
from src import db
import os, locale
from flask_login import current_user
from sqlalchemy import func, distinct, tuple_, case, desc
from flask_babel import lazy_gettext as _l, get_locale

main = Blueprint('main', __name__)

@main.post('/lang_degis')
def lang_degis():
    id = request.form.get('id')
    session['lang_code'] = id
    if id == 'tr':
        locale.setlocale(locale.LC_TIME, 'tr_TR.UTF-8')
    return session['lang_code'], 200

@main.route('/howto')
@main.route("/nasilyapilir")
def nasilyapilir():
    template = 'kilavuzlar/tr/kilavuz.html' if str(get_locale()) == 'tr' else 'kilavuzlar/en/guide.html'
    return render_template(template, baslik=_l("Nasıl Yapılır?"), isIndex=True)

@main.route('/uyari_tamamdir', methods=['POST'])
def uyari_degistir():
    aydi = request.form.get('aydi')
    path = os.path.join(current_app.config['INFERFILES_PATH'], aydi)
    if not os.path.isfile(os.path.join(path, 'siraya_alindi.txt')):
        abort(404)
    else:
        with open(os.path.join(path, 'siraya_alindi.txt'), 'w') as f:
            f.write('anlaşıldı')
        return '', 200

@main.route('/', methods=['GET', 'POST'])
def pg_landing():
    if not current_user.is_authenticated:
        _user = db.session.query(User).first()
        if _user == None:
            _user = User(username='Test User', email='dummy@dummy.com', isadmin=True, image_file='default.jpg')
            _credit = BireyselFatura(kalan_kredi=9999, user_id=1)
            _tag = Tag(name='High School', lang='en')
            _lesson = Hangiders(name='Science', lang='en')
            db.session.add_all([_user, _credit, _tag, _lesson])
            # db.session.flush()
            db.session.commit()
        login_user(_user)
    
    bitti = False
    if current_user.is_authenticated:
        path = os.path.join(current_app.config['INFERFILES_PATH'], str(current_user.id))
        if os.path.isfile(os.path.join(path, 'siraya_alindi.txt')):
            with open(os.path.join(path, 'siraya_alindi.txt'), 'r') as f:
                f = f.read()
            if str(f) == 'ilk':
                bitti = True
            else:
                bitti = False
    return render_template('paper_grading/pg_landing_page.html', isIndex=True, 
                            baslik='Paper Grading', bitti=bitti)

@main.route('/landing_veriler', methods=['GET'])
def pg_landing_veriler():
    try:
        ogretmenler = db.session.query(func.count(distinct(tuple_(PaperGradingKullanimi.user_id)))).scalar()
        kagitlar = db.session.query(func.sum(PaperGradingKullanimi.kagit_sayisi)).scalar()
        sorular = db.session.query(func.sum(\
                                    PaperGradingKullanimi.coktan_secmeli_sayisi\
                                    + PaperGradingKullanimi.dogru_yanlis_sayisi\
                                    + PaperGradingKullanimi.eslestirme_sayisi\
                                    + PaperGradingKullanimi.bosluk_doldurma_sayisi)).scalar()
        tasarruf = int(round((kagitlar * 3 ) / 60))
        ogretmenler = int(ogretmenler) + 25
        return jsonify([int(ogretmenler), int(kagitlar), int(sorular), int(tasarruf)])
    except:
        return '', 404


@main.route('/notifications')
def notifications():
    notifications = current_user.notifications.order_by(desc(Notification.yeni_mi), Notification.timestamp.desc()).limit(5)
    not_list = [{'name': n.name,'data': n.get_data(),'timestamp': n.timestamp,'id': n.id,'yeni_mi': n.yeni_mi} for n in notifications]
    return jsonify(not_list)

@main.route('/yeni_nots')
def yeni_nots():
    notifications = db.session.query(func.count(case([(Notification.yeni_mi, 1)]))).filter(Notification.user_id==current_user.id).scalar()
    return str(notifications)

@main.route('/read_notifications', methods=['POST'])
def read_notifications():
    bildirim = request.form.getlist('idler[]')
    for x in bildirim:
        x = int(x.replace('yenibild_', ''))
        _not = Notification.query.filter_by(id=x).first_or_404()
        _not.yeni_mi = False
    try:
        db.session.commit()
    except:
        db.session.rollback()
    return '', 200

@main.route('/bildirimler', methods=['GET','POST'])
def bildirimler():
    notifications = current_user.notifications.order_by(Notification.timestamp.asc()).all()
    return render_template('main/bildirimler.html',
                            notifications=notifications,
                            baslik='Bildirimler')

src/rapor/routes.py
from src.kredi.utils import kredi_hesapla
from flask import abort, current_app, url_for, redirect, render_template, Blueprint, jsonify, request, session
from flask_login import current_user, login_required
from src import db
from sqlalchemy import func
from src.rapor.utils import kazanim_performans, alphanum_key, ogrenci_kagit_sil, ogrenci_kazanim_performansi, ogrenci_okunan_sorular,\
                                ogrenci_rapor_pdf, gercek_ogrenci_ortalama, sinav_onizleme_sil, sinif_sinav_eslestir, sinif_ortalama,\
                                deep_analysis_kazanimlar, ogrenci_yeni_rapor, sinif_raporu_kredisi, sinif_raporlari_sil, _ogrenci_preview
from src.models import PaperGradingKullanimi, Okunansinav, Okunansoru, Ogrenci, Sinav, Sinif, Gercekogrenci, Sinifrapor
import boto3, os, string, unicodedata
from textwrap import wrap
from flask_babel import lazy_gettext as _l

rapor = Blueprint('rapor', __name__)
s3_client = boto3.client('s3')

@rapor.route('/pg/panel', methods=['GET', 'POST'])

def dashboard():
    kagitlar = db.session.query(func.sum(PaperGradingKullanimi.kagit_sayisi)).filter(PaperGradingKullanimi.user_id == current_user.id).scalar()
    sorular = db.session.query(func.sum(\
                                PaperGradingKullanimi.coktan_secmeli_sayisi\
                                + PaperGradingKullanimi.dogru_yanlis_sayisi\
                                + PaperGradingKullanimi.eslestirme_sayisi\
                                + PaperGradingKullanimi.bosluk_doldurma_sayisi)).filter(PaperGradingKullanimi.user_id == current_user.id).scalar()
    kredi = kredi_hesapla(current_user)
    tasarruf = 0 if kagitlar == None else int(round((kagitlar * 3 ) / 60))
    son_kullanilan_sinavlar = [Sinav.query.filter_by(id=x.sistemdeki_karsiligi).first() for x in Okunansinav.query.filter_by(lang=session['lang_code']).filter_by(user_id=current_user.id).limit(6) if x.sistemdeki_karsiligi != None]
    
    return render_template('rapor/index.html',
                            isIndex=True, 
                            baslik="Paper Grading Panel",
                            kagitlar=0 if kagitlar == None else kagitlar,
                            sorular=0 if sorular == None else sorular,
                            kredi=0 if kredi == None else kredi,
                            tasarruf=tasarruf,
                            son_kullanilan_sinavlar=son_kullanilan_sinavlar[::-1])

@rapor.get('/pg/panel/exams')
@rapor.get('/pg/panel/sinavlar')

def sinavlar():
    return render_template('rapor/sinavlar.html', isIndex=True, baslik=_l("Yapılan Sınavlar"))

@rapor.get('/pg/panel/exams/<int:id>')
@rapor.get('/pg/panel/sinavlar/<int:id>')

def sinav_goster(id):
    sinav = Okunansinav.query.filter_by(id=id).first()
    if current_user.id != sinav.user_id:
        return redirect(url_for('main.pg_landing'))
    ortalama = int(sum([o.toplam_puan for o in sinav.ogrenciler])) / len(sinav.ogrenciler)
    return render_template('rapor/sinav.html', 
                            baslik=sinav.ad, 
                            isIndex=True, 
                            sinav=sinav, 
                            ortalama=int(round(ortalama)))

@rapor.get('/pg/panel/classes')
@rapor.get('/pg/panel/siniflar')

def siniflar():
    return render_template('rapor/siniflar.html', isIndex=True, baslik=_l("Sınıflar"))

@rapor.get('/pg/panel/classes/<int:id>')
@rapor.get('/pg/panel/siniflar/<int:id>')

def sinif_goster(id):
    sinif = Sinif.query.filter_by(id=id).first()
    if current_user.id != sinif.user_id:
        return redirect(url_for('main.pg_landing'))
    return render_template('rapor/sinif.html', 
                            baslik=sinif.name, 
                            isIndex=True, 
                            sinif=sinif)

@rapor.get('/pg/panel/student/<int:id>')
@rapor.get('/pg/panel/ogrenci/<int:id>')

def ogrenci_goster(id):
    ogrenci = Ogrenci.query.filter_by(id=id).first()
    if ogrenci.sinav.user_id != current_user.id:
        return redirect(url_for('main.pg_landing'))
    if 'Hata: ' in ogrenci.ad_soyad and ogrenci.ad_soyad.endswith('.png'):
        return redirect(url_for('rapor.sinav_goster', id=ogrenci.sinav_id))
    else:
        sinav = Okunansinav.query.filter_by(id=ogrenci.sinav_id).first()
        ortalama = int(sum([o.toplam_puan for o in sinav.ogrenciler])) / len(sinav.ogrenciler)
        return render_template('rapor/ogrenci.html', 
                            baslik=_l("Paper Grading Panel"),
                            isIndex=True,
                            sinav=sinav,
                            ogrenci=ogrenci,
                            ortalama=int(round(ortalama)))

### ----> AJAX ROUTES <---- ###


@rapor.get('/rapor/panel_genel')
def panel_genel():
    sinavlar = Okunansinav.query.filter_by(user_id=current_user.id).order_by(Okunansinav.timestamp.asc()).limit(7)
    return jsonify([
        {
            'tarih': x.timestamp.strftime("%d %B %Y"),
            'ortalama':round(int(sum([o.toplam_puan for o in x.ogrenciler])) / len(x.ogrenciler), 2)
        }
        for x in sinavlar
    ])


@rapor.post('/rapor/ogrenci_preview')
def ogrenci_preview():
    id = request.form.get('id')
    ogrenci = Ogrenci.query.filter_by(id=id).first()
    if ogrenci.sinav.user_id != current_user.id:
        return abort(404)
    bilgiler = _ogrenci_preview(ogrenci)
    return {'bilgiler': sorted(bilgiler, key=lambda x: x['guven'], reverse=True)}


@rapor.post('/rapor/ogrenci_ajax')
def ogrenci_ajax():
    id = request.form.get('id')
    ogrenci = Ogrenci.query.filter_by(id=id).first()
    sinav = Okunansinav.query.filter_by(id=ogrenci.sinav_id).first()
    if sinav.user_id != current_user.id:
        return abort(404)
    sinif_kazanimlari, ogrenci_kazanimlari = ogrenci_kazanim_performansi(sinav, ogrenci)
    bilgiler = ogrenci_okunan_sorular(ogrenci)
    labels = [wrap(x, 40) for x in sinif_kazanimlari.keys()]
    bilgiler = {
        'bilgiler': sorted(bilgiler, key=lambda x: alphanum_key(x['sira'])),
        'sinif_kazanimlari':sinif_kazanimlari,
        'ogrenci_kazanimlari': ogrenci_kazanimlari,
        'labels': labels
    }
    return bilgiler


@rapor.post('/rapor/pdfolustur')
def pdfolustur():
    id = request.form.get('id')
    ogrenci = Ogrenci.query.filter_by(id=id).first()
    if ogrenci.sinav.user_id != current_user.id:
        return abort(404)
    # try:
    rapor_id = ogrenci_yeni_rapor(ogrenci)
    dispatch = {'id': rapor_id, 'lang': session['lang_code']}
    if os.environ['RUNNING_ON'] == 'localhost':
        ogrenci_rapor_pdf(dispatch)
    else:
        ogrenci_rapor_pdf.delay(dispatch)
    return '', 200
    # except:
    #     db.session.rollback()
    #     return abort(500)


@rapor.post('/rapor/rapor_kontrol')
def rapor_kontrol():
    id = request.form.get('id')
    ogrenci = Ogrenci.query.filter_by(id=id).first()
    liste = ['hata', 'bekliyor']
    if len(ogrenci.raporlar) > 0:
        rapor = ogrenci.raporlar[-1]
        if not rapor.durum in liste:
            data = current_app.config['S3_BUCKET_NAME'] + 'rapor/ogrenci/' + str(ogrenci.id) + '/' + rapor.uuid + '.' + rapor.tur
            return data
        else:
            return ogrenci.raporlar[-1].durum
    else:
        return ''


@rapor.post('/rapor/soru_bilgileri')
def soru_bilgileri():
    id = request.form.get('id')
    bilgiler = PaperGradingKullanimi.query.filter_by(okunan_sinav_id=id).first()
    sinav = Okunansinav.query.filter_by(id=id).first()
    ogrenciler = [
        {
            'id': x.id,
            'adsoyad': x.ad_soyad,
            'gercek_ogrenci': None if x.gercek_ogrenci == None else x.gercek_ogrenci.name,
            'gercek_ogrenci_id': None if x.gercek_ogrenci == None else x.gercek_ogrenci.id,
            'puan': x.toplam_puan
        }
        for x in sinav.ogrenciler
    ]
    toplam_soru = [
                    bilgiler.coktan_secmeli_sayisi / bilgiler.kagit_sayisi, 
                    bilgiler.dogru_yanlis_sayisi / bilgiler.kagit_sayisi, 
                    bilgiler.eslestirme_sayisi / bilgiler.kagit_sayisi, 
                    bilgiler.bosluk_doldurma_sayisi / bilgiler.kagit_sayisi
                ]
    _kazanimlar = kazanim_performans(sinav)
    return {
            'toplam_soru': int(sum(toplam_soru)), 
            'ad': bilgiler.ders_adi.name,
            'kagit_sayisi': bilgiler.kagit_sayisi,
            'kazanimlar': _kazanimlar,
            'sinif': sinav.sinif.name if sinav.sinif != None else None,
            'ogrenciler': ogrenciler,
            'user_siniflar': [{'ad': x.name, 'id': x.id} for x in current_user.siniflar],
            'sinif': None if sinav.sinif_id == None else sinav.sinif.name,
            'sinif_ogrenciler': None if sinav.sinif_id == None else [(x.name, x.id) for x in sinav.sinif.ogrenciler]
        }


@rapor.post('/rapor/sinavlar_ajax')
def sinavlar_ajax():
    sinavlar = Okunansinav.query.filter_by(user_id=current_user.id).filter_by(silindi_mi=False).all()
    sinavlar = [
        {
            'ad': x.ad, 
            'tarih': x.timestamp, 
            'ogrenciler':len(x.ogrenciler),
            'puan':round(int(sum([o.toplam_puan for o in x.ogrenciler])) / len(x.ogrenciler),2),
            'ders_adi': x.kullanim[0].ders_adi.name,
            'sinif': x.sinif.name if x.sinif != None else None,
            'id': x.id
        }
        for x in sinavlar
    ]
    return jsonify(sinavlar)


@rapor.post('/rapor/sinav_ad_degistir')
def sinav_ad_degistir():
    id = request.form.get('id')
    ad = request.form.get('ad')
    sinav = Okunansinav.query.filter_by(id=id).first_or_404()
    if len(ad) < 100 and len(ad) > 3:
        sinav.ad = ad
        try:
            db.session.commit()
        except:
            db.session.rollback()
            return '', 500
    else:
        abort(500)
    return '', 200


@rapor.post('/rapor/soru_cevap_degistir')
def soru_cevap_degistir():
    id = request.form.get('id')
    cevap = request.form.get('cevap')

src/templates/main/sidebar.html
<link rel="stylesheet type="text/css" href='{{ url_for("static", filename="cssler/kilavuz.css") }}'>
<link rel="stylesheet type="text/css" href='{{ url_for("static", filename="cssler/panel.css") }}'>
<script type="text/javascript" src="{{ url_for('static', filename='jsler/sidebar_button_mobile.js') }}"></script>
<script src='https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js'></script>

<div class="idocs-navigation bg-light">
    <ul class="nav flex-column">
        <li class="mb-2"><a class="karsilama-yazisi lead">{{_('Hoşgeldiniz')}}</a></li>
        <li class="nav-item"><a class="nav-link" id="panel-btn" href="{{ url_for('rapor.dashboard') }}"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="mb-1 bi bi-card-heading" viewBox="0 0 16 16">
          <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
          <path d="M3 8.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm0-5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5v-1z"/>
          </svg> Panel</a>
        </li>
        <li class="nav-item"><a class="nav-link" id="sinavlar-btn" href="{{ url_for('rapor.sinavlar') }}"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="mb-1 bi bi-file-check" viewBox="0 0 16 16">
          <path d="M10.854 6.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 8.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
          <path d="M4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4zm0 1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z"/>
          </svg> {{_('Yapılan Sınavlar')}}</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" id="siniflar-btn" href="{{ url_for('rapor.siniflar') }}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="mb-1 bi bi-people-fill" viewBox="0 0 16 16">
          <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
          <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
          <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
        </svg> {{_('Sınıflar')}}</a>
        </li>
        <li class="nav-item"><a class="nav-link" href="{{_('/nasilyapilir')}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="mb-1 bi bi-question-circle" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
          </svg> {{_('Nasıl Yapılır?')}}</a>
        </li>
        {% endif %}
        <a class="btn btn-info" id="iletisim-btn" href="{{_('/iletisim')}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="mb-1 bi bi-telephone" viewBox="0 0 16 16">
          <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
          </svg> {{_('İletişim')}}</a>
    </ul>
    </div>