src/kredi/routes.py
import os, json, re, ast, boto3, pathlib, ast, requests
from flask import render_template, url_for, flash, redirect,\
                request, abort, Blueprint, current_app, jsonify,\
                session
from flask_login import current_user, login_required
from src import db, get_locale
from src.models import User, Logo, BireyselFatura,\
                                PaperGradingKullanimi,\
                                Hangiders, Soru, Sinav, Tag, Konu, \
                                Sinav_Vote, Sinav_Kopya, Kazanim
from src.kredi.forms import TahminFormu
from src.kredi.utils import hesap, konular_ve_kademeler
from src.kredi.pdf_olustur import pdf_yazdir, parse_questions,\
                                        sorulari_gonder, sorulari_guncelle,\
                                        buckettan_sil, bucket_gorsel_ad_degistir,\
                                        bucket_sinav_kopyala, konu_ekle
from werkzeug.utils import secure_filename
from sqlalchemy import func
from urllib.parse import unquote
from src.models import generate_rand_id
from datetime import datetime
from flask_babel import lazy_gettext as _l, get_locale

kredi = Blueprint('kredi', __name__)
s3_client = boto3.client('s3')
dosya_turleri = ['.jpg','.jpeg', '.png']

@kredi.post('/kredi_tahmini')
def tahmin():
    form = TahminFormu()
    if form.validate_on_submit():
        _, data = hesap(int(form.kagit_sayisi.data), 
                        int(form.kacsayfa.data), 
                        int(form.bosluk_doldurma.data),
                        int(form.coktan_secmeli.data),
                        int(form.dogru_yanlis.data),
                        int(form.eslestirme.data))
        return jsonify(data = data)
    return jsonify(data = form.errors)

### ÖNEMLİ ###
'''
    kullanıcıların yüklediği fakat kullanmadığı görseller için bir cron job
    ya da admin sayfasına bir function yazılmalı. bu function kullanıcıların 
    yazdığı tüm soruları ve kullanıcıların directorylerindeki tüm görselleri
    eşleştirmeli, eğer görsel databaseteki bir soruda kullanılmamışsa silmelidir.
'''
### ÖNEMLİ ###

@kredi.route('/pg/exams', methods=['GET', 'POST'], endpoint='sinavlar_en')
@kredi.route('/pg/sinavlar', methods=['GET', 'POST'])

def sinavlar():
    page = request.args.get('page', 1, type=int)
    sinavlar = db.session.query(Sinav).filter_by(lang=str(get_locale())).filter(Sinav.user_id == current_user.id).order_by(Sinav.timestamp.desc())
    acik_sinavlar = db.session.query(Sinav).filter_by(lang=str(get_locale())).filter(Sinav.ozel_mi == False).count()
    return render_template('kredi/sinavlar.html', 
                            sinavlar=sinavlar.paginate(page=page, per_page=8), 
                            baslik=_l('Hazırladığınız Sınavlar'),
                            acik_sinavlar=acik_sinavlar)

@kredi.route('/pg/exam/<int:id>', methods=['GET', 'POST'])
@kredi.route('/pg/sinav/<int:id>', methods=['GET', 'POST'])

def sinav_goster(id):
    kilavuz_onay = True if not 'sinav_okuma_kilavuz_onay' in session else False
    sinav = db.session.query(Sinav).filter(Sinav.id == id).first_or_404()
    url = current_app.config['S3_BUCKET_NAME'] + f'pdfs/{str(sinav.user_id)}/' + sinav.pdf_dosyasi + '.pdf'
    
    if not current_user.is_authenticated or sinav.lang != session['lang_code']:
        session['lang_code'] = sinav.lang
        return redirect(url_for('main.pg_landing'))
    elif current_user.is_authenticated and current_user.id == sinav.user_id:
        konular, kademeler, dersler = konular_ve_kademeler()
        liste = db.session.query(Soru).filter(Soru.sinav_id == sinav.id).all()
        raw_data = sorulari_gonder(liste)
        
        bu_sinav_kademeler = [x.name for x in sinav.tags.all()]
        bu_sinav_konular = [x.name for x in sinav.konular.all()]
        
        return render_template('kredi/sinav_olustur.html', 
                                isIndex=True, 
                                baslik=sinav.baslik, 
                                data=raw_data,
                                dersler=dersler, 
                                url=url, 
                                sinav=sinav,
                                kademeler=kademeler, 
                                bu_sinav_kademeler=bu_sinav_kademeler,
                                bu_sinav_konular=bu_sinav_konular,
                                konular=konular,
                                kilavuz_onay=kilavuz_onay)
    elif sinav.ozel_mi:
        return redirect(url_for('main.pg_landing'))
    else:
        sinav_vote = db.session.query(Sinav_Vote)\
            .filter(Sinav_Vote.user_id == current_user.id)\
            .filter(Sinav_Vote.sinav_id == sinav.id).first()
        alkislanmis_mi = True if sinav_vote is not None else False
        return render_template('kredi/sinav_incele.html', 
                                isIndex=True, 
                                baslik=sinav.baslik, 
                                url=url,
                                sinav=sinav,
                                alkislanmis_mi=alkislanmis_mi)

@kredi.route('/pg/exam/create', methods=['GET', 'POST'])
@kredi.route('/pg/sinav/yeni', methods=['GET', 'POST'])

def sinav_olustur():
    kilavuz_onay = True if not 'sinav_okuma_kilavuz_onay' in session else False
    konular, kademeler, dersler = konular_ve_kademeler()
    gorsel_path = pathlib.Path(os.path.join(current_app.root_path, 'static/fpdf/pdf_files/gorseller', str(current_user.id)))
    if not gorsel_path.exists():
        os.makedirs(gorsel_path)

    ozel_sinavlar = db.session.query(func.count(Sinav.user_id == current_user.id)).filter(Sinav.ozel_mi == True).scalar()
    if ozel_sinavlar > 100:
        flash(_l('Çok fazla sınav hazırladınız, bazılarını silmeyi deneyin.'), 'danger')
        return redirect(url_for('kredi.sinavlar'))
        
    return render_template('kredi/sinav_olustur.html', 
                            isIndex=True, 
                            baslik=_l("Sınav Oluştur"), 
                            dersler=dersler, 
                            kademeler=kademeler,
                            konular=konular,
                            kilavuz_onay=kilavuz_onay)

@kredi.post('/pdf_yenile')
def pdfyenile():
    data = request.form.to_dict()
    path = os.path.join(current_app.root_path, 'static/fpdf')
    sinav = db.session.query(Sinav).filter(Sinav.user_id == current_user.id).filter(Sinav.baslik == data['baslik']).first()
    ozel_mi = True if data['gizli_mi'] == 'false' else False
    ders = db.session.query(Hangiders).filter(Hangiders.name  == data['ders']).first_or_404()
    gorsel_path = pathlib.Path(os.path.join(current_app.root_path, 'static/fpdf/pdf_files/gorseller', str(current_user.id)))
    istenmeyen_karakterler = ['^', '!', '?', '"', 'é', '}', '{', '-', '[', ']', '%', '#', '$', '£', '*', '<', '>', '=']
    
    if 'yeni_mi' in data.keys():
        var_mi = db.session.query(Sinav).filter(Sinav.user_id == current_user.id).filter(Sinav.baslik == data['baslik']).first()
        if var_mi:
            return abort(413)
    
    _baslik = ''
    for x in data['baslik']:
        if x in istenmeyen_karakterler:
            x = ''
        _baslik += x
    
    if sinav:
        if current_user.id != sinav.user_id and not current_user.isadmin:
            return abort(404)
        else:
            pdf_fn = str(current_user.id) + '-' + data['time']
            try:
                fn = pdf_yazdir(path, data, current_user.id, pdf_fn, sinav, session['lang_code'])
            except Exception as err:
                if err.args[1] == 'sayfa':
                    return abort(406)
                else:
                    return abort(500)
            sinav.pdf_dosyasi = pdf_fn
            sinav.ozel_mi = ozel_mi
            sinav.hangi_ders = ders.id
            sinav.ust_yazi = data['ust_yazi']
            sinav.alt_yazi = data['alt_yazi']
            sinav.aciklama = data['aciklama']
            if data['logo_secimi'] != '' and data['logo_secimi'] != 'None':
                sinav.logo_id = int(data['logo_secimi'])
            if sinav.uuid == None:
                sinav.uuid = generate_rand_id()
            
            if sinav.sayfa_duzeni != data['duzen']:
                sinav.sayfa_duzeni = data['duzen']

            tags = data['kademeler'].split(',')
            sinav.tags = []
            try:
                for x in tags:
                    tag_ekle = Tag.query.filter_by(lang=session['lang_code']).filter_by(name=f'{x}').first()
                    sinav.tags.append(tag_ekle)
            except:
                db.session.rollback()
                return abort(403)

            if 'konular' in data and data['konular'] != '':
                try:
                    konu_ekle(sinav, data['konular'], ders)
                except IndexError:
                    sinav.konular = []
            try:
                db.session.commit()
            except:
                db.session.rollback()
                return abort(500)

            #işlevin neden kullanılmaması gerektiğini işlevin içinde belirttim
            #eski_gorselleri_sil(gorsel_path, data, sinav)

            fn = current_app.config['S3_BUCKET_NAME'] + fn

            # celery'ye gönderilecek.
            # sorulari_guncelle.delay(sinav,data)
            sorulari_guncelle(sinav, data)

            return jsonify(fn)
    else:
        pdf_fn = str(current_user.id) + '-' + data['time']

        try:
            fn = pdf_yazdir(path, data, current_user.id, pdf_fn, '', session['lang_code'])
        except Exception as err:
            if err.args[1] == 'sayfa':
                return abort(406)
            else:
                return abort(500)

        sinav = Sinav(pdf_dosyasi=pdf_fn, ozel_mi=ozel_mi, baslik=_baslik,\
                        ust_yazi=data['ust_yazi'] if 'ust_yazi' in data else '',\
                        user_id=current_user.id, hangi_ders=ders.id,

src/templates/rapor/index.html
{% extends 'layout.html' %}
{% block betikozel %}
<script type="text/javascript" src="{{ url_for('static', filename='jsler/rapor/index.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js" integrity="sha256-bC3LCZCwKeehY6T4fFi9VfOU0gztUa+S4cnkIhVPZ5E=" crossorigin="anonymous"></script>

<div id="content">
    {% include 'main/sidebar.html' %}
    <div class="idocs-content">
        <div class="container">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Panel</h1>
        </div>

        <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-primary dp-body">
                    <div class="card-body kucuk-card">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    {{_('Okutulan Kâğıtlar')}}</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ kagitlar }}</div>
                            </div>
                            <div class="col-auto">
                                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-file-break" viewBox="0 0 16 16">
                                    <path d="M0 10.5a.5.5 0 0 1 .5-.5h15a.5.5 0 0 1 0 1H.5a.5.5 0 0 1-.5-.5zM12 0H4a2 2 0 0 0-2 2v7h1V2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v7h1V2a2 2 0 0 0-2-2zm2 12h-1v2a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-2H2v2a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2v-2z"/>
                                  </svg>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Earnings (Annual) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-success dp-body">
                    <div class="card-body kucuk-card">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                    {{_('Okutulan Sorular')}}</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ sorular }}</div>
                            </div>
                            <div class="col-auto">
                                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-check2-circle" viewBox="0 0 16 16">
                                    <path d="M2.5 8a5.5 5.5 0 0 1 8.25-4.764.5.5 0 0 0 .5-.866A6.5 6.5 0 1 0 14.5 8a.5.5 0 0 0-1 0 5.5 5.5 0 1 1-11 0z"/>
                                    <path d="M15.354 3.354a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l7-7z"/>
                                  </svg>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Tasks Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-info dp-body">
                    <div class="card-body kucuk-card">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-info text-uppercase mb-1">{{_('Kalan Kredi')}}
                                </div>
                                <div class="row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ kredi }}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-auto">
                                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-cash-stack" viewBox="0 0 16 16">
                                    <path d="M1 3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1H1zm7 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/>
                                    <path d="M0 5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V5zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V7a2 2 0 0 1-2-2H3z"/>
                                  </svg>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Pending Requests Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-warning dp-body">
                    <div class="card-body kucuk-card">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                    {{_('Kazanılan Zaman')}}</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ tasarruf }} {{_('saat')}}</div>
                            </div>
                            <div class="col-auto">
                                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-hourglass-split" viewBox="0 0 16 16">
                                    <path d="M2.5 15a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1h-11zm2-13v1c0 .537.12 1.045.337 1.5h6.326c.216-.455.337-.963.337-1.5V2h-7zm3 6.35c0 .701-.478 1.236-1.011 1.492A3.5 3.5 0 0 0 4.5 13s.866-1.299 3-1.48V8.35zm1 0v3.17c2.134.181 3 1.48 3 1.48a3.5 3.5 0 0 0-1.989-3.158C8.978 9.586 8.5 9.052 8.5 8.351z"/>
                                  </svg>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
        <div class="container-fluid">
            <div class="row">
        
                <!-- Area Chart -->
                <div class="col-xl-8 col-lg-7">
                    <div class="dp-header shadow mb-4">
                        <!-- Card Header - Dropdown -->
                        <div
                            class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">{{_('Son Sınav Ortalamaları')}}</h6>
                        </div>
                        <!-- Card Body -->
                        <div class="card-body">
                            <div class="chart-area">
                                <canvas id="myAreaChart"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
        
                <!-- Pie Chart -->
                <div class="col-xl-4 col-lg-5">
                    <div class="dp-header shadow mb-4">
                        <!-- Card Header - Dropdown -->
                        <div
                            class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">{{_('Son Kullanılan Sınavlar')}}</h6>
                        </div>
                        <!-- Card Body -->
                        <div class="card-body">
                            <ul class="list-group list-group-flush">
                                {% if son_kullanilan_sinavlar | length > 0 %}
                                    {% for x in son_kullanilan_sinavlar %}
                                        <li class="list-group-item"><a href="{{ url_for('kredi.sinav_goster', id=x.id) }}">{{ x.baslik | truncate(20) }}</a><span style="float: right;" class="badge badge-info">{{ x.konular.first().name | truncate(10) }}</span></li>
                                    {% endfor %}
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            </div>
    </div>
{% endblock betikozel %}

src/templates/rapor/sinavlar.html
{% extends 'layout.html' %}
{% block betikozel %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.2/b-2.0.0/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.11.2/b-2.0.0/datatables.min.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='jsler/rapor/sinavlar.js') }}"></script>

<div id="content">
    
    {% include 'main/sidebar.html' %}
    <div class="idocs-content">
    <div class="container">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">{{_('Yapılan Sınavlar')}}</h1>
        </div>
        {% if current_user.yapilan_sinavlar | length == 0 %}
        <div class="dp-body text-center">
            <h2>Focus on your work, let Paper Grading read your exams.</h2>
            <img src="{{ url_for('static', filename='icons/undraw_Organizing_projects_re_9p1k.svg') }}" loading="lazy" width="40%" class="my-4 illustration">
            <br>
            <a class="btn btn-outline-primary btn-lg" href="{{ url_for('paper_grading.pg_main') }}"><svg xmlns="http://www.w3.org/2000/svg" class="mb-1" width="18" height="18" fill="currentColor" class="mb-1 bi bi-file-check" viewBox="0 0 16 16">
                <path d="M10.854 6.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 8.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                <path d="M4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4zm0 1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z"/>
              </svg> {{_('Okut')}}</a>
              {% if session['lang_code'] == 'tr' %}
                <p class="lead mt-4">Düğmesine tıklayarak sınavlarınızı okutmaya başlayabilirsiniz. Başlamadan önce <a href="/nasilyapilir" class="vurgu">detaylı kılavuzu</a> okumayı unutmayın.</p>
              {% else %}
                <p class="lead mt-4">You can start grading clicking that button. Before you start, don't forget to read <a href="/howto" class="vurgu">detailed guides</a>.</p>
              {% endif %}
        </div>
        {% else %}
        <div class="col dp-body cell-border compact" style="overflow-x: auto;">
            <table id="data" class="table">
                <thead>
                    <tr>
                        <th>{{_('Sınav Adı')}}</th>
                        <th>{{_('Ne Zaman Yapıldı')}}?</th>
                        <th>{{_('Öğrenci Sayısı')}}</th>
                        <th>{{_('Ortalama Puan')}}</th>
                        <th>{{_('Ders Adı')}}</th>
                        <th>{{_('Sınıf')}}</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>
    </div>
</div>
{% endblock betikozel %}